---
logging:
  level: INFO
  loggers:
    com.mayrix: DEBUG

database:
  driverClass: org.postgresql.Driver
  user: your_db_user
  password: your_db_password
  url: jdbc:postgresql://localhost:5432/your_database_name
